In [8]:
import numpy as np


In [17]:
Ub_maxima = np.array([19.9,37.8,56.2])
Ub_minima = np.array([26.0,46.5,67.2])
Ub_maxima_diff = []
Ub_minima_diff = []
Ub_01_maxima = Ub_maxima/10
Ub_01_minima = Ub_minima/10


In [14]:
Ub_01_maxima

array([1.99, 3.78, 5.62])

In [11]:
dUmax = np.average(Ub_maxima_diff)
dUmin = np.average(Ub_minima_diff)

In [34]:
Lesefehler = 0.04
Spannungsart = 'Gleichspannung'
Bereich = 20
Auflösung = 0.01
def unsicherheitmultimiter(Spannungsart,Bereich,Auflösung,Data):
    if Spannungsart == 'Wechselspannung':
        if Bereich in [200,250]:
            Unsicherheit = Data*0.015+Auflösung*8
        if Bereich in [4,40]:
            Unsicherheit = Data*0.016+Auflösung*4
        if Bereich == 0.4:
            Unsicherheit = Data*0.02+Auflösung*10
    if Spannungsart == 'Gleichspannung':
        if Bereich in [0.2,2,20,200]:
            Unsicherheit = Data*0.005+Auflösung*8
        if Bereich in [0.4,4,40,250]:
            Unsicherheit = Data*0.008+Auflösung*8
    else:
        print('falsche Spannungsart')
    return Unsicherheit    

In [35]:
Fehler_ub_01_maxima = []
Fehler_ub_01_minima = []
for x,y in zip(Ub_01_maxima,Ub_01_minima):
    Fehler_ub_01_maxima.append(np.sqrt(unsicherheitmultimiter(Spannungsart=Spannungsart,Bereich=Bereich,Auflösung=Auflösung,Data=x)**2+Lesefehler**2))
    Fehler_ub_01_minima.append(np.sqrt(unsicherheitmultimiter(Spannungsart=Spannungsart,Bereich=Bereich,Auflösung=Auflösung,Data=y)**2+Lesefehler**2))

In [37]:
Fehler_ub_01_maxima =

[0.09844288953499893, 0.1066827539951983, 0.11526322049986285]

In [56]:
Fehler_Ub_minima_diff = []
Fehler_Ub_maxima_diff = []
for x in range(2):
    Fehler_Ub_maxima_diff.append(np.sqrt(Fehler_ub_01_maxima[x]**2+Fehler_ub_01_maxima[x+1]**2))
    Fehler_Ub_minima_diff.append(np.sqrt(Fehler_ub_01_minima[x]**2+Fehler_ub_01_minima[x+1]**2))
Fehler_Ub_maxima_diff = np.array(Fehler_Ub_maxima_diff)*10;Fehler_Ub_minima_diff = np.array(Fehler_Ub_minima_diff)*10
Fehler_Ub_minima_diff


array([1.50031872, 1.63601719])

Joining two Arrays together

In [55]:
Difference = np.array(Ub_maxima_diff + Ub_minima_diff)
Difference
Fehler_Difference = np.concatenate((Fehler_Ub_maxima_diff,Fehler_Ub_minima_diff))
Fehler_Difference

array([1.4516271 , 1.57056741, 1.50031872, 1.63601719])